import Head from 'next/head'
import Link from 'next/link';

export default function Home() {

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='choose-languange'>
                <h1>Choose Languange</h1>
                <div>
                    <Link className='language-toggle' href='/norsk'>
                        <img src='./NO-flag.svg' alt='' />
                    </Link>
                    <Link className='language-toggle' href='/english'>
                        <img src='./UK-flag.svg' alt='' />
                    </Link>
                </div>
            </div>
        </>
    )
}